#! /bin/bash

upps=$(echo $1 | tr '[:lower:]' '[:upper:]')
foo=$(echo $upps | rev)
tick=""
for (( i=0; i<${#foo}; i++ )); do
    tim="${foo:$i:1}"
    if [ "$tim" == "A" ]; then
      tick=$tick"T"
    elif [ "$tim" == "T" ]; then
      tick=$tick"A"
    elif [ "$tim" == "G" ]; then
      tick=$tick"C"
    elif [ "$tim" == "C" ]; then
      tick=$tick"G"
    elif [ "$tim" == "U" ]; then
      tick=$tick"A"
    fi

if [ "$2" == "-u" ]; then
  tick=$(echo $tick | sed 's/T/U/g')
fi

done
echo '5`- '$tick' -3`'

if command -v xclip > /dev/null; then
  echo $tick | xclip -selection clipboard
  echo "Copied to clipboard"
fi
